version: "3.3"

services:
  postgres:
    image: postgres:16
    container_name: next_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    container_name: next_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  nextjs:
    build: .
    container_name: next_app
    depends_on:
      - postgres
      - minio
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/nextdb"

      S3_ENDPOINT: "http://minio:9000"
      S3_REGION: "us-east-1"
      S3_BUCKET_NAME: "uploads"

      AWS_ACCESS_KEY_ID: "minioadmin"
      AWS_SECRET_ACCESS_KEY: "minioadmin123"

      NEXTAUTH_SECRET: "una_clave_super_segura_y_larga_que_generes"
      NEXTAUTH_URL: "http://localhost:3002"

      NODE_ENV: "production"
    ports:
      - "3002:3000"
    restart: always

volumes:
  postgres_data:
  minio_data:
